# Generated by Django 4.1.7 on 2023-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0002_alter_order_options_alter_orderinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('date', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderInfo',
            new_name='OrderItem',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=2, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], default='New', max_length=100, verbose_name='Статус'),
        ),
    ]
