# Generated by Django 4.1.7 on 2023-02-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_city_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='contact_phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='orders.address', verbose_name='Адрес'),
        ),
    ]
